# Generated by Django 5.0.1 on 2024-02-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("begin", models.DateField()),
                ("end", models.DateField()),
                ("is_active", models.BooleanField()),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
    ]
