services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data_other
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: on-failure:3
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: /django-entrypoint.sh
    restart: on-failure
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      restart: on-failure
  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env
    entrypoint: /bin/bash /usr/src/app/celery/celery.sh
    restart: on-failure

