# Generated by Django 5.0.1 on 2024-02-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "max_money_offer",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("is_active", models.BooleanField()),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
    ]
