# Generated by Django 5.0.1 on 2024-02-23 13:56

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Saloon",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("balance", models.DecimalField(decimal_places=4, max_digits=10)),
                ("characteristics", models.JSONField()),
                ("is_active", models.BooleanField()),
                ("create_time", models.DateTimeField()),
                ("update_time", models.DateTimeField()),
            ],
        ),
    ]
